### ISSUE TITLE
Problemas nas caixas de diálogo

### ISSUE THREAD

**Issue by IgorRigolon** [datazoompuc/datazoom_social_Stata#104]
Tem vários errinhos de tradução e botões que ficam escondidos:

### Caixas em português:

- [x]  Principal: Censo de 1970 a 2010, não de 1980 a 2010
- [x]  Censo: botões dos estados (RO, SE, ES) encobertos pelo vizinho, tem que aumentar o espaçamento
- [x]  Censo: título da caixa está CENSO, seria melhor Censo
- [x]  PNAD: botões de compatibilidade estão pulando fora da caixinha, tem que aumentar o comprimento
- [x] PNAD Anual: labels estão feios, trocar 2012_visita1 por 2012 visita 1, o mesmo pra trimestre. Ficaria  mais bonitinho ter uma caixinha para cada ano.
- [x]  PNAD Anual: link do guia de suplementos não funciona
- [x] PNAD Covid: título está PNAD COVID19, diferente do resto onde chamamos de PNAD Covid
- [x] POF: Caixa de Bases Padronizadas: Unidade de consumo é grande demais e atropela a caixinha de Pessoas, tem que aumentar o espaçamento
- [x] POF: Gastos Selecionados: caixinha do tipo de identificação está toda espremida
- [x] POF: Gastos Selecionados: botão de Labels em Inglês fica escondido, algo em cima está roubando o espaço
- [x] POF: TRs: Nada cabe no espaço; mesmo problema com Labels em Inglês

### Caixas em inglês

- [x] Principal: Censo 1980 -> 1970; Texto da PME o y está cortado na parte de baixo; Texto da PNAD não coube
- [x] Censo: Título está gigante, trocar por Censo; vários problemas com acentos e espaçamento
- [x] PME Antiga: título grande
- [x] PNAD Anual: mesmos problemas da em português
- [x] PNAD Covid: título
- [x] POF: mesmas coisas

### Geral
- [x] Precisamos padronizar os botões de "Dados" e "Salvando", algumas caixas fogem

**Comment by lauratregadas** [comment]
Also fixed on both languages' main dlg boxes:
- [x] hyperlink vertical alignment w the rest of text
On portuguese main dlg box:
- [x] spacing issues

**Comment by lauratregadas** [comment]
To do:
- [ ] spacing PNS
- [ ] spacing POF main

**Comment by lauratregadas** [comment]
**Padrão dos botões**

Em português
- Título: Bases de dados
- Dados originais...
- Salvando...

Em inglês:
- Título: Databases
- Original files...
- Saving...

**Comment by lauratregadas** [comment]
**Outros padrões**

- Títulos o mais curtos possíveis: Censo, PNAD Covid, PNS, etc.
- Margem de 5 unidades de cada lado e também entre frames, exceto no main  e no main da POF em que são todos colados

Como fazer "Labels em inglês" + PUC-Rio - Departamento de Economia lado a lado: 
- Labels em inglês a 5 da margem principal, tamanho horizontal 150
- Dpto de Economia a 160 da margem principal, tamanho é tamanho horizontal da caixa -5-160, aí terá margem de 5 na direita também
- Ambos com posição vertical = tamanho vertical da caixa - 20
