### ISSUE TITLE
Error in 90s Old PME

### ISSUE THREAD

**Issue by IgorRigolon** [datazoompuc/datazoom_social_Stata#106]
Complaint sent by e-mail:

The code
```
datazoom_pmeantiga, years( 1992 ) original(...) saving(...) nid
```
returns an "invalid file specification" error.

## Solution

In line 52 of our datazoom_pmeantiga.ado script, the code:

```
tempfile `PME`1'`mm'D`
```

must be changed to

```
tempfile PME`1'`mm'D,
```

as the local PME`1'`mm'D wasn’t yet defined.

**Comment by lauratregadas** [comment]
I tried implementing this and it did not fix the problem. I then got a 198 error about PMEBAmes, which is valid given we were sometimes referring to months as mm and sometimes as mes. I changed it all to mm but still got thrown a 198 error - this time, claiming invalid file specification for 1992 households.
