### ISSUE TITLE
PNADC (and maybe others) - Add value labels

### ISSUE THREAD

**Issue by IgorRigolon** [datazoompuc/datazoom_social_Stata#109]
We already provide variable labels, explaining what each variable is, in PT and EN. However, for categorical variables, we don't provide value labels, explaining what each level of the variable is. 

This would require manually pouring through the dictionary and creating labels (in both languages) for each variable, and I believe this can't be automated easily. However, not that many variables will require this, and the returns are big: final output will become much nicer.

**Comment by jasonyu623** [comment]
Hi, is there a way now to use program to get the value labels?

**Comment by IgorRigolon** [comment]
@jasonyu623 Hi, not yet. But we recently remade all of our PNADC dictionaries in an automated fashion, so I think we can do the same for the value labels. If it works out we'll have them in a few weeks.

**Comment by IgorRigolon** [comment]
This was implemented in #127. There's also a [release](https://github.com/datazoompuc/datazoom_social_Stata/releases/tag/enhancement) to show it off.
