### ISSUE TITLE
PNAD-C Annual 2018

### ISSUE THREAD

**Issue by abdrazakovaa** [datazoompuc/datazoom_social_Stata#115]
Hello,

I am working with PNAD-C Annual visits. I noticed that there is a problem with year 2018, some variables are shifted. For example when I tab VD4010 that is "Grupamentos de atividade principal do empreendimento do trabalho principal da semana de referência para pessoas de 14 anos ou mais de idade" in the dictionary with 10 categories, it shows up as a binary 0,1 variable. 

![pnadc2018](https://github.com/datazoompuc/datazoom_social_Stata/assets/102962872/34f388b8-a2dd-4c4a-8ff6-b236cd82491a)

Thank you!
Best regards,

**Comment by IgorRigolon** [comment]
Hi @abdrazakovaa, the dictionary we were using for the 1st visit of 2018 was full of mistakes. It's not that the variables were swapped, but the data types were wrong, so only the first digit was showing. If you reinstall the package, it should be fixed now:

![dict](https://github.com/datazoompuc/datazoom_social_Stata/assets/77173467/7708bef0-97e3-4bee-91a4-5a0e2445b61d)

If there's anything else wrong, feel free to let us know. Sorry for the inconvenience and thank you for opening the Issue.
