### ISSUE TITLE
PNAD-C 2016-2019 visit 5

### ISSUE THREAD

**Issue by abdrazakovaa** [datazoompuc/datazoom_social_Stata#117]
Hello, 

Thank you very much for your help.
I wanted to work with PNAD-C 2016-2019 visit 5 and I noticed irregularities with variables: tab V2005 (role within a household) should provide values between 1-19 but it produces the following:

![datazoom_query](https://github.com/datazoompuc/datazoom_social_Stata/assets/102962872/18a3dd16-847b-4e86-8568-3120e8143159)

I have updated datazoom_social and changed var names from English to Portuguese but the problem persists.

Thank you!
Best regards,

**Comment by mariana-nmartins** [comment]
Hi, @abdrazakovaa,
Just letting you know that we have been working to solve the problem you pointed out. Thank you for bringing it to our attention!
Best

**Comment by IgorRigolon** [comment]
We have rebuilt all of our PNADC dictionaries, and I believe this error has been fixed in the latest version of the package. If you find something wrong again, please reach out and it will be easier for us to fix it this time around.
