### ISSUE TITLE
Opção comp81 parece não funcionar. 

### ISSUE THREAD

**Issue by jpazvd** [datazoompuc/datazoom_social_Stata#121]
Ola, 

Estou tentado usar a opcao comp81 com o comando datazoom_pnad, no entando ela nao parece estar funcionando de maneira consistente.

Nos anos 1981-1990 eu so consigo gerar o arquivo de pessoas; nos anos 1992-2015 a mesma opcao parece so funcionar para o arquivo domicilios (ver abaixo a syntax e erro que encontro). 

Segue abaixo uma tabela com o resumo do que eu consegui rodar.

Como a mesma tambela tambem indica, as opcoes comp92 e ncomp funciaram perfeitamente.

Qualquer ajuda sera muito bem vinda.

          - frame survey_results: list

               +--------------------------------------------------------------------------------------------------------------------------+
               | ctry           survey   svyyear   svyname   master~t   adaptV~t   adapt   original   stata   docs   progs        modules |
               |--------------------------------------------------------------------------------------------------------------------------|
            1. |  BRA    bra_1981_pnad      1981      PNAD        v01                             1       3     24       0   both dom pes |
            2. |  BRA    bra_1981_pnad      1981      PNAD        v01        v01   dtz81          0       1      0       0            pes |
            3. |  BRA    bra_1982_pnad      1982      PNAD        v01                             1       3     16       0   both dom pes |
            4. |  BRA    bra_1982_pnad      1982      PNAD        v01        v01   dtz81          0       1      0       0            pes |
            5. |  BRA    bra_1983_pnad      1983      PNAD        v01                             1       3     13       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
            6. |  BRA    bra_1983_pnad      1983      PNAD        v01        v01   dtz81          0       1      0       0            pes |
            7. |  BRA    bra_1984_pnad      1984      PNAD        v01                             1       3     10       0   both dom pes |
            8. |  BRA    bra_1984_pnad      1984      PNAD        v01        v01   dtz81          0       1      0       0            pes |
            9. |  BRA    bra_1985_pnad      1985      PNAD        v01                             1       3     11       0   both dom pes |
           10. |  BRA    bra_1985_pnad      1985      PNAD        v01        v01   dtz81          0       1      0       0            pes |
               |--------------------------------------------------------------------------------------------------------------------------|
           11. |  BRA    bra_1986_pnad      1986      PNAD        v01                             1       3      6       0   both dom pes |
           12. |  BRA    bra_1986_pnad      1986      PNAD        v01        v01   dtz81          0       1      0       0            pes |
           13. |  BRA    bra_1987_pnad      1987      PNAD        v01                             0       3      0       0   both dom pes |
           14. |  BRA    bra_1987_pnad      1987      PNAD        v01        v01   dtz81          0       1      0       0            pes |
           15. |  BRA    bra_1988_pnad      1988      PNAD        v01                             1       3      1       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
           16. |  BRA    bra_1988_pnad      1988      PNAD        v01        v01   dtz81          0       1      0       0            pes |
           17. |  BRA    bra_1989_pnad      1989      PNAD        v01                             0       3      0       0   both dom pes |
           18. |  BRA    bra_1989_pnad      1989      PNAD        v01        v01   dtz81          0       1      0       0            pes |
           19. |  BRA    bra_1990_pnad      1990      PNAD        v01                             0       3      0       0   both dom pes |
           20. |  BRA    bra_1990_pnad      1990      PNAD        v01        v01   dtz81          0       1      0       0            pes |
               |--------------------------------------------------------------------------------------------------------------------------|
           21. |  BRA    bra_1990_pnad      1990      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           22. |  BRA    bra_1992_pnad      1992      PNAD        v01                             1       3     51       0   both dom pes |
           23. |  BRA    bra_1992_pnad      1992      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           24. |  BRA    bra_1992_pnad      1992      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           25. |  BRA    bra_1993_pnad      1993      PNAD        v01                             1       3     48       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
           26. |  BRA    bra_1993_pnad      1993      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           27. |  BRA    bra_1993_pnad      1993      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           28. |  BRA    bra_1995_pnad      1995      PNAD        v01                             1       3     49       0   both dom pes |
           29. |  BRA    bra_1995_pnad      1995      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           30. |  BRA    bra_1995_pnad      1995      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
           31. |  BRA    bra_1996_pnad      1996      PNAD        v01                             1       3     48       0   both dom pes |
           32. |  BRA    bra_1996_pnad      1996      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           33. |  BRA    bra_1996_pnad      1996      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           34. |  BRA    bra_1997_pnad      1997      PNAD        v01                             1       3     51       0   both dom pes |
           35. |  BRA    bra_1997_pnad      1997      PNAD        v01        v01   dtz81          0       1      0       0            dom |
               |--------------------------------------------------------------------------------------------------------------------------|
           36. |  BRA    bra_1997_pnad      1997      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           37. |  BRA    bra_1998_pnad      1998      PNAD        v01                             1       3     89       0   both dom pes |
           38. |  BRA    bra_1998_pnad      1998      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           39. |  BRA    bra_1998_pnad      1998      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           40. |  BRA    bra_1999_pnad      1999      PNAD        v01                             1       3     48       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
           41. |  BRA    bra_1999_pnad      1999      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           42. |  BRA    bra_1999_pnad      1999      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           43. |  BRA    bra_2001_pnad      2001      PNAD        v01                             1       3      4       0   both dom pes |
           44. |  BRA    bra_2001_pnad      2001      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           45. |  BRA    bra_2001_pnad      2001      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
           46. |  BRA    bra_2001_pnad      2001      PNAD        v02                             1       3     56       0   both dom pes |
           47. |  BRA    bra_2001_pnad      2001      PNAD        v02        v01   dtz81          0       1      0       0            dom |
           48. |  BRA    bra_2001_pnad      2001      PNAD        v02        v01   dtz92          0       3      0       0   both dom pes |
           49. |  BRA    bra_2002_pnad      2002      PNAD        v01                             1       3      4       0   both dom pes |
           50. |  BRA    bra_2002_pnad      2002      PNAD        v01        v01   dtz81          0       1      0       0            dom |
               |--------------------------------------------------------------------------------------------------------------------------|
           51. |  BRA    bra_2002_pnad      2002      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           52. |  BRA    bra_2002_pnad      2002      PNAD        v02                             1       3     54       0   both dom pes |
           53. |  BRA    bra_2002_pnad      2002      PNAD        v02        v01   dtz81          0       1      0       0            dom |
           54. |  BRA    bra_2002_pnad      2002      PNAD        v02        v01   dtz92          0       3      0       0   both dom pes |
           55. |  BRA    bra_2003_pnad      2003      PNAD        v01                             1       3      4       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
           56. |  BRA    bra_2003_pnad      2003      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           57. |  BRA    bra_2003_pnad      2003      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           58. |  BRA    bra_2003_pnad      2003      PNAD        v02                             1       3     54       0   both dom pes |
           59. |  BRA    bra_2003_pnad      2003      PNAD        v02        v01   dtz81          0       1      0       0            dom |
           60. |  BRA    bra_2003_pnad      2003      PNAD        v02        v01   dtz92          0       3      0       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
           61. |  BRA    bra_2004_pnad      2004      PNAD        v01                             1       3      4       0   both dom pes |
           62. |  BRA    bra_2004_pnad      2004      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           63. |  BRA    bra_2004_pnad      2004      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           64. |  BRA    bra_2004_pnad      2004      PNAD        v02                             1       3     55       0   both dom pes |
           65. |  BRA    bra_2004_pnad      2004      PNAD        v02        v01   dtz81          0       1      0       0            dom |
               |--------------------------------------------------------------------------------------------------------------------------|
           66. |  BRA    bra_2004_pnad      2004      PNAD        v02        v01   dtz92          0       3      0       0   both dom pes |
           67. |  BRA    bra_2005_pnad      2005      PNAD        v01                             1       3      4       0   both dom pes |
           68. |  BRA    bra_2005_pnad      2005      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           69. |  BRA    bra_2005_pnad      2005      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           70. |  BRA    bra_2005_pnad      2005      PNAD        v02                             1       3     56       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
           71. |  BRA    bra_2005_pnad      2005      PNAD        v02        v01   dtz81          0       1      0       0            dom |
           72. |  BRA    bra_2005_pnad      2005      PNAD        v02        v01   dtz92          0       3      0       0   both dom pes |
           73. |  BRA    bra_2006_pnad      2006      PNAD        v01                             1       3      4       0   both dom pes |
           74. |  BRA    bra_2006_pnad      2006      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           75. |  BRA    bra_2006_pnad      2006      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
           76. |  BRA    bra_2006_pnad      2006      PNAD        v02                             1       3     12       0   both dom pes |
           77. |  BRA    bra_2006_pnad      2006      PNAD        v02        v01   dtz81          0       1      0       0            dom |
           78. |  BRA    bra_2006_pnad      2006      PNAD        v02        v01   dtz92          0       3      0       0   both dom pes |
           79. |  BRA    bra_2007_pnad      2007      PNAD        v01                             1       3      4       0   both dom pes |
           80. |  BRA    bra_2007_pnad      2007      PNAD        v01        v01   dtz81          0       1      0       0            dom |
               |--------------------------------------------------------------------------------------------------------------------------|
           81. |  BRA    bra_2007_pnad      2007      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           82. |  BRA    bra_2007_pnad      2007      PNAD        v02                             1       3     14       0   both dom pes |
           83. |  BRA    bra_2007_pnad      2007      PNAD        v02        v01   dtz81          0       1      0       0            dom |
           84. |  BRA    bra_2007_pnad      2007      PNAD        v02        v01   dtz92          0       3      0       0   both dom pes |
           85. |  BRA    bra_2008_pnad      2008      PNAD        v01                             1       3      4       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
           86. |  BRA    bra_2008_pnad      2008      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           87. |  BRA    bra_2008_pnad      2008      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           88. |  BRA    bra_2008_pnad      2008      PNAD        v02                             1       3     14       0   both dom pes |
           89. |  BRA    bra_2008_pnad      2008      PNAD        v02        v01   dtz81          0       1      0       0            dom |
           90. |  BRA    bra_2008_pnad      2008      PNAD        v02        v01   dtz92          0       3      0       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
           91. |  BRA    bra_2009_pnad      2009      PNAD        v01                             1       3      4       0   both dom pes |
           92. |  BRA    bra_2009_pnad      2009      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           93. |  BRA    bra_2009_pnad      2009      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
           94. |  BRA    bra_2009_pnad      2009      PNAD        v02                             1       3     15       0   both dom pes |
           95. |  BRA    bra_2009_pnad      2009      PNAD        v02        v01   dtz81          0       1      0       0            dom |
               |--------------------------------------------------------------------------------------------------------------------------|
           96. |  BRA    bra_2009_pnad      2009      PNAD        v02        v01   dtz92          0       3      0       0   both dom pes |
           97. |  BRA    bra_2011_pnad      2011      PNAD        v01                             1       3     25       0   both dom pes |
           98. |  BRA    bra_2011_pnad      2011      PNAD        v01        v01   dtz81          0       1      0       0            dom |
           99. |  BRA    bra_2011_pnad      2011      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
          100. |  BRA    bra_2011_pnad      2011      PNAD        v02                             1       3     12       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
          101. |  BRA    bra_2011_pnad      2011      PNAD        v02        v01   dtz81          0       1      0       0            dom |
          102. |  BRA    bra_2011_pnad      2011      PNAD        v02        v01   dtz92          0       3      0       0   both dom pes |
          103. |  BRA    bra_2012_pnad      2012      PNAD        v01                             1       3     25       0   both dom pes |
          104. |  BRA    bra_2012_pnad      2012      PNAD        v01        v01   dtz81          0       1      0       0            dom |
          105. |  BRA    bra_2012_pnad      2012      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
          106. |  BRA    bra_2012_pnad      2012      PNAD        v02                             1       3     22       0   both dom pes |
          107. |  BRA    bra_2012_pnad      2012      PNAD        v02        v01   dtz81          0       1      0       0            dom |
          108. |  BRA    bra_2012_pnad      2012      PNAD        v02        v01   dtz92          0       3      0       0   both dom pes |
          109. |  BRA   bra_2012_pnadc      2012     PNADC        v01                             0       1      4       0            tri |
          110. |  BRA    bra_2013_pnad      2013      PNAD        v01                             1       3     27       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
          111. |  BRA    bra_2013_pnad      2013      PNAD        v01        v01   dtz81          0       1      0       0            dom |
          112. |  BRA    bra_2013_pnad      2013      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
          113. |  BRA   bra_2013_pnadc      2013     PNADC        v01                             0       1      4       0            tri |
          114. |  BRA    bra_2014_pnad      2014      PNAD        v01                             1       3     29       0   both dom pes |
          115. |  BRA    bra_2014_pnad      2014      PNAD        v01        v01   dtz81          0       1      0       0            dom |
               |--------------------------------------------------------------------------------------------------------------------------|
          116. |  BRA    bra_2014_pnad      2014      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
          117. |  BRA   bra_2014_pnadc      2014     PNADC        v01                             0       1      4       0            tri |
          118. |  BRA    bra_2015_pnad      2015      PNAD        v01                             1       3     28       0   both dom pes |
          119. |  BRA    bra_2015_pnad      2015      PNAD        v01        v01   dtz81          0       1      0       0            dom |
          120. |  BRA    bra_2015_pnad      2015      PNAD        v01        v01   dtz92          0       3      0       0   both dom pes |
               |--------------------------------------------------------------------------------------------------------------------------|
          121. |  BRA   bra_2015_pnadc      2015     PNADC        v01                             0       1      4       0            tri |
          122. |  BRA   bra_2016_pnadc      2016     PNADC        v01                             0       1      4       0            tri |
          123. |  BRA   bra_2017_pnadc      2017     PNADC        v01                             0       1      4       0            tri |
          124. |  BRA   bra_2018_pnadc      2018     PNADC        v01                             0       1      4       0            tri |
          125. |  BRA   bra_2019_pnadc      2019     PNADC        v01                             0       1      4       0            tri |
               |--------------------------------------------------------------------------------------------------------------------------|
          126. |  BRA   bra_2020_pnadc      2020     PNADC        v01                             0       1      4       0            tri |
          127. |  BRA   bra_2021_pnadc      2021     PNADC        v01                             0       1      4       0            tri |
          128. |  BRA   bra_2022_pnadc      2022     PNADC        v01                             0       1      4       0            tri |
          129. |  BRA   bra_2023_pnadc      2023     PNADC        v01                             0       1      4       0            tri |
          130. |  BRA   bra_2024_pnadc      2024     PNADC        v01                             0       1      4       0            tri |
               +--------------------------------------------------------------------------------------------------------------------------+

Codigo exemplo com o erro:

PNAD 2001 (reponderacao_2001_2009)

. datazoom_pnad, years( 2001) original(C:\data\IBGE_FTP_Download\PNAD\reponderacao_2001_2009\2001\dados) saving(D:\datalib) pes comp81
D:\datalib
Anos selecionados: 2001

Gerando bases de pessoas ...
c:\ado\plus/d/dict.dta
(file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000002.tmp not found)
(file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000001.tmp not found)
file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000001.tmp saved as .dta format
(0 changes made to v0101)
uf: all characters numeric; replaced as byte
...

(378,837 missing values generated)
(119,642 changes made to v4756)
(161,081 real changes made)
(93,011 changes made to v9042)
(164 changes made to v9058)
trabalhou_sem not found
r(111); t=16.27 17:43:55

PNAD 2002 (reponderacao_2001_2009)

. datazoom_pnad, years( 2002) original(C:\data\IBGE_FTP_Download\PNAD\reponderacao_2001_2009\2002\dados) saving(D:\datalib) pes comp81
D:\datalib
Anos selecionados: 2002

Gerando bases de pessoas ...
c:\ado\plus/d/dict.dta
(file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000002.tmp not found)
(file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000001.tmp not found)
file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000001.tmp saved as .dta format
Extraindo 2002...
uf: all characters numeric; replaced as byte
(5,442 changes made to uf)
...

(147,885 differences between v9001 and trabalhou_semana)
(237,567 missing values generated)
(2,671 real changes made)
variable ramo_negocio_sem not found
r(111); t=18.80 17:41:47

PNAD 2003 (reponderacao_2001_2009)

. datazoom_pnad, years( 2003) original(C:\data\IBGE_FTP_Download\PNAD\reponderacao_2001_2009\2003\dados) saving(D:\datalib) pes comp81
D:\datalib
Anos selecionados: 2003

Gerando bases de pessoas ...
c:\ado\plus/d/dict.dta
(file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000002.tmp not found)
(file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000001.tmp not found)
file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000001.tmp saved as .dta format
Extraindo 2003...
uf: all characters numeric; replaced as byte
...

(208,236 real changes made)
(149,330 differences between v9001 and trabalhou_semana)
(235,547 missing values generated)
(2,772 real changes made)
variable ramo_negocio_sem not found
r(111); t=21.21 17:42:19

PNAD 2009 (reponderacao_2001_2009)

. datazoom_pnad, years( 2009) original(C:\data\IBGE_FTP_Download\PNAD\reponderacao_2001_2009\2009\dados) saving(D:\datalib) pes comp81
D:\datalib
Anos selecionados: 2009

Gerando bases de pessoas ...
c:\ado\plus/d/dict.dta
(file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000002.tmp not found)
(file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000001.tmp not found)
file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000001.tmp saved as .dta format
Extraindo 2009...
uf: all characters numeric; replaced as byte
(5,838 changes made to uf)
uf was byte now str2
...
(153,447 differences between v9001 and trabalhou_semana)
(245,940 missing values generated)
(3,310 real changes made)
variable ramo_negocio_sem not found
r(111); t=22.52 17:45:06

PNAD 2009 (reponderacao_2001_2012)

. datazoom_pnad, years( 2009) original(C:\data\IBGE_FTP_Download\PNAD\reponderacao_2001_2012\2009\dados) saving(D:\datalib) pes comp81
D:\datalib
Anos selecionados: 2009

Gerando bases de pessoas ...
c:\ado\plus/d/dict.dta
(file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000002.tmp not found)
(file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000001.tmp not found)
file C:\Users\azeve\AppData\Local\Temp\ST_10a5c_000001.tmp saved as .dta format
Extraindo 2009...
uf: all characters numeric; replaced as byte
(5,838 changes made to uf)
uf was byte now str2
...
(238,515 real changes made)
(153,447 differences between v9001 and trabalhou_semana)
(245,940 missing values generated)
(3,310 real changes made)
variable ramo_negocio_sem not found
r(111); t=22.44 17:45:59

**Comment by lauratregadas** [comment]
Olá! Não consegui reproduzir seu erro. Testei já com as mudanças do pull request #132, que talvez também tenha resolvido esse problema. Com os dados de 2003, consegui gerar as pessoas de pessoas, de domicílios e ambas mergeadas com a opção comp81. Sei que o merge de fato funcionou porque os arquivos têm tamanhos diferentes. Ainda preciso obter dados do período 1980-1990 para ver se está funcionando.

**Comment by lauratregadas** [comment]
Parece que há sim um problema para o períodode 1981-1990, tanto para domicílios quanto para pessoas. Mesmo sem pedir as bases mergeadas, muitas observações são apagadas: ~70 mil para pessoas 1988 e ~190 mil para domicílios 1988.

**Comment by lauratregadas** [comment]
Consegui os dados de 1981-1990 e conseui gerar os arquivos sem receber mensagem de erro. @jpazvd, pode tentar de novo e ver se dessa vez tudo funciona?
