### ISSUE TITLE
Censo -- erros no dicionário

### ISSUE THREAD

**Issue by lauratregadas** [datazoompuc/datazoom_social_Stata#130]
Enviada via Instagram:

Eu peguei erros de digitação no dicionário do Censo Demográfico! No Censo de 2010, a coluna V6033 (e não V0633!) é a idade da pessoa. V0633 é o curso mais elevado que a pessoa concluiu (indicado por um código), V0634 indica a conclusão ou não desse curso (não é V0636, que é cheia de NA). No Censo de 2000, a coluna que indica o código do município (número de 7 dígitos, em que os 2 primeiros são referentes à UF) é V1103 (e não V0103, como aparece no dicionário!). Por favor, pessoal do DataZoom, esses erros vieram do próprio IBGE, mas vocês podem avisar pelo DataZoom que existem esses erros no dicionário do Censo.

**Comment by IgorRigolon** [comment]
Nos dicionários que de fato usamos para ler os dados (em `.dct`), os nomes das variáveis estão corretos. Apenas encontrei esse erro [neste link](https://www.econ.puc-rio.br/datazoom/censoArq.html), que de fato está desatualizado. A planilha atualizada mora no site do IBGE.

No Censo de 2000, a variável de município é, sim, V0103. Não vejo porque concluir que se trata de um erro de digitação, vários arquivos de documentação do IBGE põem município como V0103.
