### ISSUE TITLE
arquivos da pnad continua baixados pelo data zoom com diversos missings

### ISSUE THREAD

**Issue by marconinelson** [datazoompuc/datazoom_social_Stata#134]
olá, baixei todas as pnads contínuas pelo datazoom para o stata18. Nos arquivos gerados, diversas variáveis apareceram com missing values, incluindo o ano e muitas outras, como a V4010 e a V4013, que são de meu interesse. Mas não se resume a elas. Queria ajuda para corrigir isso, baixei de várias formas, usando mesmo diretório, diretórios diferentes, anos diferentes, mais de um ano, um ano só, sem identificação do indivíduo, com identificação... enfim o resultado é sempre o mesmo. O processo gera muitos missing values. a única diferença que encontrei são nas pnads de anos mais recentes, nas quais a id do painel apresenta valores, enquanto nas pndas dos anos iniciais são missing values. mas para as demais variáveis já citadas, e muitas outras, o arquivo gerado sempre apresenta missing values. Vocês podem me ajudar, por favor ?

obrigado, Nelson

**Comment by IgorRigolon** [comment]
Foi um erro na construção dos dicionários mesmo, mudamos há pouco para uma forma automatizada de montar os dicionários em .dct. O problema está resolvido na nova versão.
