### ISSUE TITLE
Região Metropolitana de São Paulo

### ISSUE THREAD

**Issue by pablotadeu** [datazoompuc/datazoom_social_Stata#49]
O IBGE fornece os microdados do estado de São Paulo divididos em dois arquivos: um para a região metropolitana e outro para o resto do estado. Acredito que tenha que incluir no código do Censo uma opção para leitura de cada um destes arquivos. Ao rodar para a Região Metropolitana aparece o erro 
![image](https://user-images.githubusercontent.com/79670059/161546732-f373ec93-0976-4ad1-8b42-c5b3735bbffa.png)

**Comment by MariaVictoriaMesq** [comment]
Para fazer a leitura dos dados do estado de SP (Região Metropolitana e outras regiões) basta colocar os arquivos das duas pastas em um única pasta e selecioná-la como  _original_.
