### ISSUE TITLE
Pacote compatível com versão Stata 13

### ISSUE THREAD

**Issue by FranciscoCavalcanti** [datazoompuc/datazoom_social_Stata#53]
**Issue** abaixo levantado pelo usuário Ely José de Mattos

Oi, pessoal.
Tudo bem?

Estou tentando instalar o pacote do Datazoom no Stata 13, mas está retornando o seguinte erro:

```
Received fatal alert: protocol_version
https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/ either
  1)  is not a valid URL, or
  2)  could not be contacted, or
  3)  is not a Stata download site (has no stata.toc file).
r(5100);
```

Já tentei em diversas máquinas, com o Stata 13, e não funciona. Pode ser algo com a versão?

Obrigado!

Abs

Ely

**Comment by MariaVictoriaMesq** [comment]
Olá,

A instalação do pacote através do GitHub não funciona para a versão 13 do Stata. 

Uma alternativa para utilizar o nosso pacote seria baixar os arquivos manualmente e adicioná-los à pasta "ado".

**Comment by MariaVictoriaMesq** [comment]
Olá,

A instalação do pacote através do GitHub não funciona para a versão 13 do Stata. 

Uma alternativa para utilizar o nosso pacote seria baixar os arquivos manualmente e adicioná-los à pasta "ado".

Agradecemos o seu contato.
