### ISSUE TITLE
Erro ao tentar baixar PNS 2019

### ISSUE THREAD

**Issue by eduardonilson** [datazoompuc/datazoom_social_Stata#54]
Oi, 
Tudo bem? Estou tentando baixar os microdados da PNS 2019 usando  o pacote do Datazoom no Stata 17, mas está retornando o seguinte erro:

. datazoom_pns, original(D:\PNS 2019) saving(D:\PNS 2019) year( 2019 )
/ is not a valid command name
r(199);

(instalei o txt original no diretório D:\PNS 2019)

Obrigado e abraços!
Eduardo

**Comment by FranciscoCavalcanti** [comment]
Olá @eduardonilson 

Houve uma alteração no pacote no qual aparentemente resolver o problema com PNS.

Testei o comando com Stata 16 e o resultado foi satisfatório. Ver imagem abaixo.

![Screenshot 2022-05-12 at 09 12 51](https://user-images.githubusercontent.com/38975126/168072202-bc89c6b2-ebd9-4239-975f-e93c1a947afe.png)

Por favor, reinstale o pacote e nos avise se o problema persiste.

**Comment by eduardonilson** [comment]
Muito obrigado! Funcionou perfeitamente
