### ISSUE TITLE
Instalação do pacato Data Zoom

### ISSUE THREAD

**Issue by Laudelina23** [datazoompuc/datazoom_social_Stata#57]
Olá, quando vou instalar o pacote Data Zoom no Stata 16 aparece o seguinte erro:

. net install datazoom_social, from("https://raw.githubusercontent.com/datazoomp
> uc/datazoom_social_stata/master/") force
PKIX path validation failed: java.security.cert.CertPathValidatorException: vali
> dity check failed
https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/ eith
> er
  1)  is not a valid URL, or
  2)  could not be contacted, or
  3)  is not a Stata download site (has no stata.toc file).
r(5100);

Obrigada!

**Comment by MariaVictoriaMesq** [comment]
Olá, @Laudelina23 

Você só teve esse problema com o download do nosso repositório ou isso também aconteceu com outros?

Fizemos o teste em 3 computadores diferentes com o Stata 16 e a instalação funcionou em todos. Talvez seja um problema com o seu Stata ou conexão de internet.

Uma alternativa para utilizar o nosso pacote seria baixar os arquivos manualmente e adicioná-los à pasta "ado".
