### ISSUE TITLE
Erro 671 na instalação

### ISSUE THREAD

**Issue by leaosnatalia** [datazoompuc/datazoom_social_Stata#64]
O que devo fazer? Queria uma ajuda na instalação. Tentei instalar de todas as formas (no Stata 12), mas sempre aparece o seguinte erro:

. net install datazoom_social, from("https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/") force
unknown network protocol
https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/ either
  1)  is not a valid URL, or
  2)  could not be contacted, or
  3)  is not a Stata download site (has no stata.toc file).

**Comment by FranciscoCavalcanti** [comment]
Olá @leaosnatalia

Esse Issue é similar ao [Issue 57](https://github.com/datazoompuc/datazoom_social_Stata/issues/57).

O problema provavelmente se dá porque Stata nas versões inferior ao 13 não comportam "https". Por isso infelizmente não é possível baixar os arquivos do pacote diretamente para essas versões.

Uma solução nesses casos é salvar manualmente os arquivos do **datazoom_social** diretamente na sua pasta local onde o Stata lê as rotinas de código.

Para saber onde está localizada a pasta onde Stata lê as rotinas no seu computador, basta rodar no seu console o seguinte comando `adopath`. Em seguida você deverá salvar cada arquivo do repositório **datazoom_social** na pasta correspondente a letra inicial de cada arquivo. Por exemplo, para os arquivos que começam com a letra “**d**” como o arquivo datazoom_social.ado deverá ser salvo na pasta "**c:\ado\plus\d**". Já os arquivos que começam com a letra “**p**” como pnadcontinua.dct deverá ser salvo na pasta "**c:\ado\plus\p**"

**Comment by frebelos** [comment]
Olá! Estou com o mesmo problema. Não consegui encontrar como/onde fazer o download manual dos arquivos. Poderiam me ajudar? Obrigada!
