### ISSUE TITLE
POF 2017

### ISSUE THREAD

**Issue by sinaradovalle** [datazoompuc/datazoom_social_Stata#75]
Bom dia,

Quando importo os gastos selecionados da POF 2017 no Stata aparece a mensagem observações não encontrada nesse nível de ID. O problema ocorre em todos os níveis. Como resolver?

**Comment by FranciscoCavalcanti** [comment]
Olá @sinaradovalle!

Pelo que entendi, o erro que você está enfrentando pode estar relacionado ao fato de que você ainda não baixou e descompactou os dados brutos da POF 2017. Portanto, sugiro que você primeiro verifique se baixou e extraiu os dados brutos da POF para uma pasta em seu computador.

Depois de fazer isso, ao tentar importar os dados para o Stata, você pode usar o botão "Dados originais..." na caixa de diálogo para selecionar a pasta em que salvou os dados brutos. Isso deve ajudar o Stata a localizar os arquivos necessários para importar os dados corretamente.

Espero que isso ajude! Se você ainda tiver problemas, por favor, informe mais detalhes para que possamos tentar encontrar uma solução mais específica para o seu caso.

**Comment by sinaradovalle** [comment]
Boa noite Francisco. Muito obrigada pelo retorno.

1 - Já baixei e salvei numa pasta os dados brutos da POF 2017.
2- Consigo importar os dados das Bases Padronizadas e Tipos de registros sem problemas.
3- O erro é quando uso gastos selecionados na POF 2017. Mesmo eu usando o botão "Dados originais..." “salvando...” os dados não veem de forma desagregada.  Esse erro ocorre especificamente quando importo da POF 2017. Se eu fizer com a POF 2008 eu consigo importar dados sem erro.
4-


ABAIXO UM EXEMPLO. Estou tentando importar dados desagregados de  energia elétrica a nível de domicílio.

1 – instalei - net install datazoom_social, from("https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/") force
2- db datazoom_pof
3- escolhi o ano de 2017/18 e opção gastos selecionados.
***@***.***
E


4 – . selecionei a opção de domicílio
       . outros gastos
       .energia elétrica
       . cliquei no botão (...clique para adicioná-lo)
       . selecionei a pasta Dados_20221226 na qual está no meu computador e que contém os txt com os dados brutos da POF. (Esses dados baixei no site do IBGE, microdados POF 2017/18).
***@***.***

***@***.***

Depois selecionei a pasta dados gerados na qual ficará salvo as novas bases

***@***.***

Feito isso, cliquei no botão submit


***@***.***

E por final, aparece a seguinte mensagem de erro que está em vermelho “ sem observações para energia_elétrica a esse nível de id”. OBS: ISSO OCORRE PARA QUALQUER TIPO DE IDENTIFICAÇÃO.
***@***.***


Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Francisco ***@***.***>
Enviado:segunda-feira, 27 de fevereiro de 2023 17:05
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [datazoompuc/datazoom_social_Stata] POF 2017 (Issue #75)


Olá @sinaradovalle<https://github.com/sinaradovalle>!

Pelo que entendi, o erro que você está enfrentando pode estar relacionado ao fato de que você ainda não baixou e descompactou os dados brutos da POF 2017. Portanto, sugiro que você primeiro verifique se baixou e extraiu os dados brutos da POF para uma pasta em seu computador.

Depois de fazer isso, ao tentar importar os dados para o Stata, você pode usar o botão "Dados originais..." na caixa de diálogo para selecionar a pasta em que salvou os dados brutos. Isso deve ajudar o Stata a localizar os arquivos necessários para importar os dados corretamente.

Espero que isso ajude! Se você ainda tiver problemas, por favor, informe mais detalhes para que possamos tentar encontrar uma solução mais específica para o seu caso.

**Comment by FranciscoCavalcanti** [comment]
Olá @sinaradovalle!

Obrigado por relatar o problema no Github. Gostaria de informar que o problema que você encontrou já foi resolvido no mais novo Pull Request aceito (#79). Recomendo que você reinstale o pacote usando o seguinte comando:

```
net install datazoom_social, from("https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/") force
```

Isso garantirá que os arquivos sejam atualizados e que o usuário possa abrir os dados desejados sem problemas. Se você tiver alguma outra dúvida ou problema, por favor, não hesite em entrar em contato conosco.

Obrigado por usar o Datazoom Social para Stata.

Atenciosamente,
