### ISSUE TITLE
POF 2017 - Pacote de internet, celular e TV

### ISSUE THREAD

**Issue by mateuseconomus** [datazoompuc/datazoom_social_Stata#76]
Através de opção "Gastos selecionados" e para qualquer tipo de identificação, não é possível extrair os dados sobre gastos com pacote de celular, TV e internet. Ao tentar realizar a extração, obtenho o seguinte erro:

"Sem observações para Pacote_de_telefone a esse nível de id"

**Comment by FranciscoCavalcanti** [comment]
Olá @mateuseconomus, sua questão se parece bastante com o issue #75.  

Com base na sua mensagem, parece que você está enfrentando um problema ao tentar importar os gastos selecionados da POF 2017 no Stata, já que a mensagem "Sem observações para Pacote_de_telefone a esse nível de id". Para solucionar esse problema, é possível que ainda não tenha baixado e descompactado os dados brutos da POF para uma pasta em seu computador.

Para resolver esse problema, sugiro que você comece verificando se baixou e extraiu corretamente os dados brutos da POF. Após isso, ao tentar importar os dados para o Stata, você pode selecionar a pasta em que salvou os dados brutos, usando o botão "Dados originais..." na caixa de diálogo. Essa ação pode ajudar o Stata a encontrar os arquivos necessários para importar os dados corretamente.

Espero que essas orientações ajudem a resolver o problema. Se precisar de mais informações, por favor, fique à vontade para fornecer detalhes adicionais para que possamos fornecer uma solução mais precisa.

**Comment by FranciscoCavalcanti** [comment]
Olá @mateuseconomus!

Obrigado por relatar o problema no Github. Gostaria de informar que o problema que você encontrou já foi resolvido no mais novo Pull Request aceito (#79). Recomendo que você reinstale o pacote usando o seguinte comando:

```
net install datazoom_social, from("https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/") force
```

Isso garantirá que os arquivos sejam atualizados e que o usuário possa abrir os dados desejados sem problemas. Se você tiver alguma outra dúvida ou problema, por favor, não hesite em entrar em contato conosco.

Obrigado por usar o Datazoom Social para Stata.

Atenciosamente,

**Comment by sinaradovalle** [comment]
Obrigada!!!

Att,
Sinara do Valle
(24) 99275-1731




________________________________
De: Francisco Cavalcanti ***@***.***>
Enviado: quinta-feira, 2 de março de 2023 11:08
Para: datazoompuc/datazoom_social_Stata ***@***.***>
Cc: sinaradovalle ***@***.***>; Manual ***@***.***>
Assunto: Re: [datazoompuc/datazoom_social_Stata] POF 2017 - Pacote de internet, celular e TV (Issue #76)


Olá @mateuseconomus<https://github.com/mateuseconomus>!

Obrigado por relatar o problema no Github. Gostaria de informar que o problema que você encontrou já foi resolvido no mais novo Pull Request aceito (#79<https://github.com/datazoompuc/datazoom_social_Stata/pull/79>). Recomendo que você reinstale o pacote usando o seguinte comando:

net install datazoom_social, from("https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/") force



Isso garantirá que os arquivos sejam atualizados e que o usuário possa abrir os dados desejados sem problemas. Se você tiver alguma outra dúvida ou problema, por favor, não hesite em entrar em contato conosco.

Obrigado por usar o Datazoom Social para Stata.

Atenciosamente,

**Comment by mateuseconomus** [comment]
Muito obrigado pela ajuda, Francisco! Funcionou aqui.
