### ISSUE TITLE
POF 2017 - SERVIÇOS E TAXAS

### ISSUE THREAD

**Issue by sinaradovalle** [datazoompuc/datazoom_social_Stata#81]
Bom dia!
* Serviços e taxas - id (dom) - exemplo
local Água_e_esgoto v_DT_1102036 6002 / 6002 6018 / 6018 12017 / 12017 12027 / 12027
local Energia_elétrica v_DT_1102031 6001 / 6001
local Gás_doméstico v_DT_1102035 6003 / 6003 7001 / 7001
LOCAL ALOSTOS_SERVICOS_E_TAXAS V_DT_1102037 6005 / 6006 6999 / 6999 10999 / 10999 12003 / 12003 12005 / 12012 12014 / 12016 12018 / 12026 12028 / 12030 12022 / 12016
local Pacote_de_telefone_tv_internet v_DT_1102034 6007 / 6017 28030 / 28030
local Telefone_celular v_DT_1102033 44001 / 44003 44007 / 44007
local Telefone_fixo v_DT_1102032 6004 / 6004

Com relação as variáveis acima algumas não aparece valores nem a nível de id( dom) ou (uc) ou (pess).

 sum v_DT_110203_tot v_DT_1102036_tot v_DT_1102031_tot v_DT_1102035_tot v_DT_1102037_tot v_DT_1102034_tot v_DT_110 2033_tot v_DT_1102032_tot

![sum](https://user-images.githubusercontent.com/125669883/224292068-6a14acaf-d33e-4d42-ac0b-a6dde4e395bf.jpg)

**Comment by lauratregadas** [comment]
Hello! We are currently working on this issue
- First, we checked whether data exists at the "domicílio" level. It does, as well it exists for "Unidade de Consumo". Some of it does not exist for "Pessoas". So, this is not causing the problem
- Then, we checked whether "local" was wrong, but it is correct for each of these variables. That was confirmed matching 2017 POF's .ado file's code with the "Tradutor_Despesa_Geral" sheet from the "Tradutores de Tabelas" folder,
- Finally, we figured the final values were being transformed to zero as V9011 is missing for all entries of these variables. This should be fixed very soon.

Thank you for reporting the error and for your patience! Please note values for many variables that end with "nm" will still be zero, as these reflect non-monetary values.

**Comment by lauratregadas** [comment]
![image](https://github.com/user-attachments/assets/9b62e2df-b362-400f-bc26-2a677933e5f7)

Problem solved! V9011 refers to the number of months the individual purchased the good in a year. Therefore, it is part of the annualization. However, it is only applicable for "quadros" 10 and 19.  Line 819 also used it for other "quadro"s. The image shows the updated results. Indeed, variables ending in `nm` are still 0, but that is expected. Results presented at the uc level.

Obrigada pela paciência! Um erro de código estava causando o problema -  a variável V9011 era usada na anualização sempre, sendo que só deveria ser usada para os quadros 10 e 19. Tudo parece estar funcionando agora. Resultados da imagem a nível de Unidade de Consumo
