### ISSUE TITLE
ICT survey PNADC 2016-2017

### ISSUE THREAD

**Issue by abdrazakovaa** [datazoompuc/datazoom_social_Stata#82]
Hello, sorry,
I have successfully accessed trimestral and annual data with datazoom_social stata, thank you. 
But when I try to work with supplementary surveys like PNAD Continua Annual data 2016_visita4 datazoom does not upload converted file into the folder. 
In stata command window I write: db datazoom_social
In the options window I pick: PNAD continua, annual
I get the following message:
"Esta versão do pacote datazoom_pnadcont_anual é compatível com a última versão dos microdados divulgado pelo IBGE em 16/07/2020
 As bases de dados foram salvas na pasta XXX" 
but the file is neither converted nor uploaded. Could you please help me with this? 
Thank you!

**Comment by FranciscoCavalcanti** [comment]
Hi @abdrazakovaa 

The latest accepted Pull Request (PR) for the datazoom_social Stata repository, available at [PR #87](https://github.com/datazoompuc/datazoom_social_Stata/pull/87), includes all the necessary updates. These updates address the issue you mentioned regarding the supplementary surveys not being uploaded.

To resolve this problem, please update your local copy of the datazoom_social Stata package by pulling the latest changes from the repository `net install datazoom_social, from("https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/") force`. After updating, run the command db datazoom_social again, select the PNAD continua, annual options, and the converted file should be uploaded correctly.

If you need further assistance, feel free to provide more details. We're here to help.

Thank you,
