### ISSUE TITLE
Erro 601 na importação do censo de 1980

### ISSUE THREAD

**Issue by ariaker** [datazoompuc/datazoom_social_Stata#92]
Ao usar a função para preparar o censo de 1980, parece-me que o programa importa os arquivos com a extensão errada: .dta no lugar de .dbf.

`datazoom_censo, years(1980 ) ufs( RO AC AM RR PA AP MA PI CE RN PB PE AL SE BA MG ES RJ SP PR SC RS MS MT GO DF) original(C:\microdados\1980_txts) saving(C:\microdados\1980) both
`

O erro que surge é justamente o 601:
`Tipo(s) de Registro:`
 `Domicílios e Pessoas`
`C:\microdados\1980`
`RO`
`Extraindo 1980 RO - RO ...`
`C:\ado/d/dict.dta`
`(note: file C:\Users\A\AppData\Local\Temp\ST_01000001.tmp not found)`
`file C:\microdados\1980_txts/CD80DOM11.dta`
`    not found`
`r(601);
`

**Comment by lauratregadas** [comment]
I don't have access to the data, so I can't try to reproduce this error. However, looking at the code, it looks like nothing is wrong. In the datazoom_censo.ado file, there are no mentions to .dbf. Moreover, every `findfile` command refers to a .dta file

**Comment by lauratregadas** [comment]
I managed to get the data and reproduced the error. Indeed, line 245 of datazoom_cendo.ado file tries to open .dta files when it should open .dbf files

**Comment by lauratregadas** [comment]
Olá! Essa issue será resolvida ao fecharmos o pull request #131. Por algum motivo, o código tentava puxar aqrquivos .dta ao invés de .dbf. Trocamos `use` por `import dbase` para puxar arquivo .dbf e usamos uma tempfile para mergear os arquivos de domicílio e de pessoas, que são separados no formato .dbf. Executei o código no meu computador com os dados .dbf e ele rodou sem erros. Parece estar funcionando corretamente agora.
