### ISSUE TITLE
banco PNS 2019 diferente do diccionario 

### ISSUE THREAD

**Issue by pola1982** [datazoompuc/datazoom_social_Stata#97]
Oi,
Eu consegui salvar o banco da PNS 2019 (versao 20220525 - site do IBGE) em Stata 15.1 da forma em que vocês orientam, porém percebi que para algumas variaveis (por ex. Q079, Q080, Q08109) os codigos sao diferentes do dicionario para essa mesma versao do banco. 
Ha alguma atualização quanto a isso? o que pode estar acontecendo?
Obrigada

**Comment by pola1982** [comment]
Segue o comando que estou utilizando:
![print](https://github.com/datazoompuc/datazoom_social_Stata/assets/148160764/ba8de253-be78-40e6-b4d1-24628a168d79)

**Comment by malubraun** [comment]
Resolvido no PR #100 - Updating PNS 2019 Dictionaries
