### ISSUE TITLE
Atualizar PNAD Continua

### ISSUE THREAD

**Issue by pablotadeu** [datazoompuc/datazoom_social_Stata#98]
O IBGE divulgou os microdados *anuais* da PNAD-Contínua:
- PNADC 2022 - Trimestre 4 e 
- PNADC 2022 - Visita 1
- PNAD 2022 - Visita 5

**Comment by IgorRigolon** [comment]
- [ ] PNADC 2022 - Trimestre 4
- [ ] PNADC 2022 - Visita 1
- [X] PNADC 2022 - Visita 5
